// lib/data.ts
import { Service, Testimonial } from "@/types";

export const SERVICES: Service[] = [
  {
    id: "websites",
    icon: "Globe",
    title: "Business Websites & Landing Pages",
    shortDesc: "High-converting, SEO-optimized websites that make your brand unforgettable.",
    problem: "Your competitors are winning customers online while you're invisible.",
    solution: "We build fast, modern websites tailored to your brand — designed to convert visitors into paying customers.",
    benefit: "More leads, better first impressions, and a 24/7 digital salesperson working for you.",
    features: ["SEO-optimized structure", "Mobile-first design", "Performance score 90+", "CMS integration", "Lead capture forms", "Analytics setup"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "web-apps",
    icon: "LayoutDashboard",
    title: "Web Applications & SaaS",
    shortDesc: "Custom dashboards, admin panels, and SaaS platforms built to scale.",
    problem: "Off-the-shelf software doesn't fit your workflow and costs a fortune in licenses.",
    solution: "We architect and build custom web applications that match your exact business logic — from MVP to enterprise scale.",
    benefit: "Full control over your software, reduced operational cost, and a competitive advantage no one can copy.",
    features: ["Custom admin dashboards", "Role-based access control", "REST & GraphQL APIs", "Real-time features", "Third-party integrations", "Cloud deployment"],
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "mobile-apps",
    icon: "Smartphone",
    title: "Mobile Applications",
    shortDesc: "Native-quality Android & iOS apps that your users will love.",
    problem: "Your customers are on mobile, but you have no app — you're losing engagement and revenue.",
    solution: "We build cross-platform mobile apps with React Native that feel native on both Android and iOS.",
    benefit: "Reach your customers anywhere, anytime, with push notifications, offline support, and app store presence.",
    features: ["React Native cross-platform", "Push notifications", "Offline-first capability", "App Store & Play Store publishing", "Biometric auth", "Payment integration"],
    color: "from-purple-500 to-pink-600",
  },
  {
    id: "gym-software",
    icon: "Dumbbell",
    title: "Gym Management Software",
    shortDesc: "Purpose-built software to run your gym like clockwork.",
    problem: "Managing memberships on spreadsheets is costing you time, money, and members.",
    solution: "Our gym management system handles memberships, payments, attendance, and communication — all in one place.",
    benefit: "Save 10+ hours/week, reduce no-shows by 40%, and give members a premium digital experience.",
    features: ["Member management & profiles", "Automated fee reminders", "Attendance & check-in", "Trainer scheduling", "Payment tracking", "WhatsApp notifications"],
    color: "from-orange-500 to-red-600",
  },
  {
    id: "school-software",
    icon: "GraduationCap",
    title: "School / Education Management",
    shortDesc: "Complete EMS to manage students, fees, staff, and academics.",
    problem: "Paper-based school management is error-prone, time-consuming, and opaque to parents.",
    solution: "A unified school management system for admissions, fees, attendance, grades, and parent communication.",
    benefit: "Paperless operations, real-time parent visibility, and admin time cut by 60%.",
    features: ["Student lifecycle management", "Fee collection & receipts", "Attendance with reports", "Parent mobile portal", "Timetable management", "Exam & marksheet generation"],
    color: "from-green-500 to-teal-600",
  },
  {
    id: "erp-crm",
    icon: "Network",
    title: "ERP / CRM Solutions",
    shortDesc: "Enterprise-grade systems that connect your entire business.",
    problem: "Disconnected tools, manual data entry, and zero visibility across departments kill growth.",
    solution: "We build custom ERP and CRM systems that unify operations, sales, inventory, HR, and finance.",
    benefit: "Single source of truth, faster decisions, and operations that scale without adding headcount.",
    features: ["Sales pipeline & lead tracking", "Inventory management", "HR & payroll modules", "Financial reporting", "Multi-branch support", "Custom workflows"],
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: "api-development",
    icon: "Code2",
    title: "API Development & Integration",
    shortDesc: "Robust, documented APIs and seamless third-party integrations.",
    problem: "Your systems don't talk to each other, causing data silos and manual workarounds.",
    solution: "We design and build RESTful and GraphQL APIs, plus integrate payment gateways, CRMs, ERPs, and any third-party service.",
    benefit: "Automated data flow, zero duplication, and a tech foundation that grows with your business.",
    features: ["REST & GraphQL APIs", "Payment gateway integration", "SMS & WhatsApp APIs", "OAuth & SSO", "Webhook systems", "API documentation"],
    color: "from-violet-500 to-indigo-600",
  },
  {
    id: "custom-software",
    icon: "Wrench",
    title: "Custom Software Development",
    shortDesc: "If you can imagine it, we can build it. Tailored to your exact needs.",
    problem: "Your business has unique processes that no standard software can handle.",
    solution: "We listen, architect, and build exactly what you need — no bloat, no compromises, just the right solution.",
    benefit: "A competitive moat through proprietary software that your competitors simply can't buy.",
    features: ["Discovery & requirement analysis", "System architecture design", "Agile development sprints", "QA & testing", "Deployment & DevOps", "Long-term maintenance"],
    color: "from-rose-500 to-orange-600",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Rajesh Kulkarni",
    role: "Owner",
    company: "IronEdge Fitness",
    businessType: "Gym & Fitness Center",
    content: "Before Protonity, I was managing 200+ memberships on WhatsApp and a notebook. Renewals were missed, payments were forgotten, and I was stressed every day. Now everything is automated. I get alerts, members get reminders, and I can see my entire business on my phone.",
    result: "Reduced admin time by 12 hours/week, recovered ₹80,000 in pending dues within 30 days.",
    rating: 5,
    initials: "RK",
    avatarColor: "from-orange-500 to-red-600",
  },
  {
    id: "2",
    name: "Priya Sharma",
    role: "Principal",
    company: "Sunrise Academy",
    businessType: "K-12 School",
    content: "We had 500 students, paper registers, and angry parents who had no idea about fees or attendance. Protonity built us a system in 6 weeks. Parents now get instant updates, fee collection is online, and my staff actually has time to focus on teaching.",
    result: "Fee collection improved by 35%, parent satisfaction scores went from average to excellent.",
    rating: 5,
    initials: "PS",
    avatarColor: "from-green-500 to-teal-600",
  },
  {
    id: "3",
    name: "Amit Desai",
    role: "Founder & CEO",
    company: "SwiftLogix",
    businessType: "Logistics Startup",
    content: "We needed a custom operations dashboard to manage our delivery network across 3 cities. Every agency we talked to wanted 6 months and 15 lakhs. Protonity delivered in 10 weeks at a fraction of the cost — and the quality is something we're proud to show investors.",
    result: "Launched MVP in 10 weeks, secured seed funding 2 months later using the platform as a demo.",
    rating: 5,
    initials: "AD",
    avatarColor: "from-blue-500 to-indigo-600",
  },
  {
    id: "4",
    name: "Sneha Patil",
    role: "Marketing Director",
    company: "GreenLeaf Organics",
    businessType: "E-commerce / D2C Brand",
    content: "Our old website was slow, ugly, and not converting. Protonity redesigned it with a focus on conversions, speed, and mobile experience. They explained every decision in plain English. No jargon, no ego — just results.",
    result: "Website speed improved by 3x, mobile conversion rate increased by 22% in 60 days.",
    rating: 5,
    initials: "SP",
    avatarColor: "from-purple-500 to-pink-600",
  },
  {
    id: "5",
    name: "Mohammed Ansari",
    role: "Director",
    company: "Ansari Constructions",
    businessType: "Real Estate & Construction",
    content: "We needed a CRM to track leads from 8 projects simultaneously. Protonity built exactly what we described, trained our team, and stayed available for 3 months post-launch to fix anything that came up. That support alone is worth everything.",
    result: "Lead follow-up time dropped from 3 days to 2 hours. Converted 4 high-value projects directly from the CRM.",
    rating: 5,
    initials: "MA",
    avatarColor: "from-cyan-500 to-blue-600",
  },
  {
    id: "6",
    name: "Kavita Joshi",
    role: "Co-founder",
    company: "NutriTrack",
    businessType: "Health Tech Startup",
    content: "Protonity built our entire platform — backend APIs, web dashboard, and mobile app — with a small, sharp team. What impressed me most was how they thought about scalability from day one. We now have 4,000 users and zero performance issues.",
    result: "Scaled to 4,000 active users with zero downtime. Raised Pre-Seed round 4 months after launch.",
    rating: 5,
    initials: "KJ",
    avatarColor: "from-violet-500 to-indigo-600",
  },
];

export const STATS = [
  { value: "50+", label: "Projects Delivered" },
  { value: "30+", label: "Happy Clients" },
  { value: "4+", label: "Years Experience" },
  { value: "100%", label: "Client Retention" },
];

export const TECH_STACK = [
  { category: "Frontend", items: ["React", "Next.js", "TypeScript", "Tailwind CSS"] },
  { category: "Backend", items: ["Node.js", "Python", "Express", "Django"] },
  { category: "Mobile", items: ["React Native", "Expo", "Android", "iOS"] },
  { category: "Database", items: ["PostgreSQL", "MongoDB", "MySQL", "Redis"] },
  { category: "Cloud", items: ["AWS", "Vercel", "Docker", "Nginx"] },
  { category: "Integrations", items: ["Razorpay", "Stripe", "Twilio", "Firebase"] },
];

export const INDUSTRIES = [
  { icon: "Dumbbell", label: "Gyms & Fitness", desc: "Membership automation & scheduling" },
  { icon: "GraduationCap", label: "Schools & Institutes", desc: "Student management & fees" },
  { icon: "Rocket", label: "Startups", desc: "MVP to scalable product" },
  { icon: "Building2", label: "SMEs & Enterprises", desc: "ERP, CRM & custom workflows" },
  { icon: "ShoppingBag", label: "E-commerce", desc: "Stores, payments & logistics" },
  { icon: "Heart", label: "Healthcare", desc: "Patient portals & clinic systems" },
];

export const WHY_CHOOSE = [
  {
    icon: "ShieldCheck",
    title: "Reliable Delivery",
    desc: "We commit to timelines and stick to them. 90% of our projects launch on or before deadline.",
  },
  {
    icon: "MessageSquare",
    title: "Clear Communication",
    desc: "No ghosting, no jargon. Daily updates, WhatsApp-friendly, and always a real person to talk to.",
  },
  {
    icon: "TrendingUp",
    title: "Built to Scale",
    desc: "Every solution is architected for growth — whether you have 100 or 100,000 users.",
  },
  {
    icon: "IndianRupee",
    title: "Transparent Pricing",
    desc: "Fixed-price quotes, zero hidden costs. You know exactly what you're paying for and why.",
  },
  {
    icon: "Headphones",
    title: "Post-Launch Support",
    desc: "We don't disappear after go-live. 3 months of free support comes standard with every project.",
  },
  {
    icon: "MapPin",
    title: "Local + Global Expertise",
    desc: "Based in Jalna, Maharashtra — we understand Indian business needs and build for global standards.",
  },
];
